### ISSUE TITLE
CoAP Server-side Example Application

### ISSUE THREAD

**Issue by bsmelo** [ARMmbed/mbed-coap#49]
Hello,

I'm sorry if this is not the appropriate channel for this kind of question---I couldn't find any other.
From what I understand of ARMmbed's coap-related repos, I guess `ARMmbed/coap-service`, `ARMmbed/mbed-client-c` and `ARMmbed/mbed-client-linux-example` all uses this library underneath; but I couldn't find a sample application, in any of those repos, which I could simply build, run, and be able to send something such as a `GET .well-known/core` to port `5683` and receive a response from it. Is there any such sample application, exposing at least one sample coap resource, you could provide or point me to?

Thanks in advance!
Bruno Melo.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCLT-2505

**Comment by teetak01** [comment]
Hi @bsmelo have you checked how https://github.com/armmbed/mbed-os-example-client example application works? It uses https://github.com/armmbed/mbed-client library, which internally uses mbed-coap?

Both coap-service and mbed-client-c are mainly internal APIs used by mbed-client/nanostack.

**Comment by bsmelo** [comment]
Hi @teetak01, thanks for answering.
I did have a look at that repo, `mbed-os-example-client`, but I can't run that application without an specific hardward, right? That's why I though `mbed-client-linux-example` was the way to go, since apparently I could run it on Linux, and it looks like it uses mbed-coap internally as well... But it seems that I would need an account on mbed Device Connector... Or can I just use a different LWM2M Server implementation to which the `mbed-client-linux-example` would register itself?

**Comment by JanneKiiskila** [comment]
@bsmelo - any updates from your side? 

The old examples are now deprecated (as is the mbed Device Connector service) and replaced with Pelion - we have the [mbed-cloud-client-example](https://github.com/ARMmbed/mbed-cloud-client-example) (supporting multiple OSes, including Linux, FreeRTOS, ...) and [Pelion.com](http://www.pelion.com) service (free tier available for trials).

Linux on PC documentation available [here](https://www.pelion.com/docs/device-management/current/connecting/linux-on-pc.html).

Please let us know if you need more or if we can close this ticket.

**Comment by bsmelo** [comment]
Hello, thanks for the follow up!

Great to see the project keeps evolving, but I was at the time looking for sample applications to be used during my masters research. That was finished 2 years ago and I've moved to other projects so, unfortunatelly, I won't be able to check the new samples.

I believe the ticket can be closed, and I thank you guys again!
