### ISSUE TITLE
Ack packet don't return

### ISSUE THREAD

**Issue by zesoxi** [ARMmbed/mbed-coap#77]
Hi,
I'm trying to write a coap server over stm32 with mbed os.
I'm want to use coap to send and receive big data from the PC to the MCU with the blockwise feature.
When my python script(CoAPhon) sending a PUT request, I'm passing the packet to the function sn_coap_protocol_parse. The function do no't return ACK even when the payload is really short and all the payload arrived in one packet. When I'm sending long packet, the function returns a ACK for every packet arrived except the last one.
The problem is that the script is waiting for the ack.
I tried to debug the library but didn't understood if i'm using the library wrong or that I don't understand the protocol.
I'm enabled the blockwise feature and limited the payload size to 128 bytes, in the python script as well.
I would like to hear a suggestion.

Thank you.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCLT-3207

**Comment by anttiylitokola** [comment]
Hi! 
Thanks for your report. Could you repeat your use case with the logs, maybe those would reveal something?
